### ISSUE TITLE
SISTEMA DE PAGAMENTO SPLIT

### ISSUE THREAD

**Issue by diegobencke** [claudiosmweb/woocommerce-pagarme#11]
Olá Claudio, Contratei o Split da Pagar-me.
Tenho um Marketplace em Woocommerce e quero que os pagamentos de minhas comissões e o valor de cada cliente seja dividido automaticamente.
A Pagar-me tem esta solução e já contratei.
A questão é que eles me mandaram um código para configurar cada recebedor, só que não tenho ideia de onde colocar este código ( https://docs.pagar.me/api/?php#criando-um-recebedor )

Consegue me ajudar?

**Comment by claudiosmweb** [comment]
Não tem integração com isso ainda neste plugin.
