### ISSUE TITLE
woocommerce-pagarme em precisar do WooCommerce Extra Checkout Fields for Brazil

### ISSUE THREAD

**Issue by filipedeschamps** [claudiosmweb/woocommerce-pagarme#12]
@claudiosmweb você sabe dizer se há algum mal comportamento se utilizarmos este módulo sem o WooCommerce Extra Checkout Fields for Brazil?

Obrigado!

**Comment by claudiosmweb** [comment]
Provavelmente, vai ficar sem número os endereços, sem bairro e etc.

**Comment by filipedeschamps** [comment]
Que estranho, ao instalar tudo pelo wordpress recebo toda hora a mensagem como esta:

![image](https://cloud.githubusercontent.com/assets/4248081/12598943/bba96308-c474-11e5-9fe3-42c0829c94a4.png)

Ele é mandatório mesmo?

**Comment by claudiosmweb** [comment]
Acabei de ver, vai precisar sim, esta como dependencia.

**Comment by filipedeschamps** [comment]
Certo, você acha que é possível remover esta dependência?

Digo isto pois dependendo do lojista de fato estes campos não são mais obrigatórios.

**Comment by claudiosmweb** [comment]
E como fica o anti-fraude?
Acabei adicionando isso por causa dele.

**Comment by filipedeschamps** [comment]
Correto, agora fazemos no modelo opcional. Quando o cliente vende digital goods, por exemplo, podemos para vários casos desabilitar o antifraude e estes dados não se tornam mais obrigatórios.

**Comment by claudiosmweb** [comment]
Suave então, vou remover como dependencia.

**Comment by filipedeschamps** [comment]
Cara sensacional, a galera de digital goods vai pirar :+1:

**Comment by claudiosmweb** [comment]
Estou testando aqui, retornou isso daqui:

```json
{
  "errors": [
    {
      "parameter_name": "customer[address][neighborhood]",
      "type": "invalid_parameter",
      "message": "bairro está faltando"
    },
    {
      "parameter_name": "customer[address][street_number]",
      "type": "invalid_parameter",
      "message": "número da rua está faltando"
    }
  ],
  "url": "/transactions",
  "method": "post"
}
```

Bom já avisar ai do seu lado :P

**Comment by filipedeschamps** [comment]
@claudiosmweb vou desabilitar o seu antifraude. A conta está cadastrada em qual email?

**Comment by claudiosmweb** [comment]
contato@claudiosmweb.com

**Comment by filipedeschamps** [comment]
@claudiosmweb já está desabilitado.

Talvez está sendo enviado parcialmente o objeto de `customer.address`?

**Comment by claudiosmweb** [comment]
Tentei enviar sem os dados de número e bairro, também tentei enviar vazio e deu erro para os dois.

**Comment by filipedeschamps** [comment]
Vou fazer um teste batendo diretamente na api usando sua chave de teste, ok?

**Comment by claudiosmweb** [comment]
Beleza

**Comment by filipedeschamps** [comment]
Veja:

`POST` `https://api.pagar.me/1/transactions`
``` js
{
    "api_key": "{{api_key}}",
    "amount": 10000,
    "card_number": "4532224403590610",
    "card_expiration_date": "1050",
    "card_holder_name": "Filipe Deschamps",
    "card_cvv": "123"
}
```

**Retorno**

```
{
  "object": "transaction",
  "status": "paid",
  "refuse_reason": null,
  "status_reason": "acquirer",
  "acquirer_response_code": "00",
  "acquirer_name": "development",
  "authorization_code": "277241",
  "soft_descriptor": null,
  "tid": 1453859253648,
  "nsu": 1453859253648,
  "date_created": "2016-01-27T01:47:33.000Z",
  "date_updated": "2016-01-27T01:47:33.000Z",
  "amount": 10000,
  "installments": 1,
  "id": 365433,
  "cost": 200,
  "card_holder_name": "Filipe Deschamps",
  "card_last_digits": "0610",
  "card_first_digits": "453222",
  "card_brand": "visa",
  "postback_url": null,
  "payment_method": "credit_card",
  "capture_method": "ecommerce",
  "antifraud_score": null,
  "boleto_url": null,
  "boleto_barcode": null,
  "boleto_expiration_date": null,
  "referer": "api_key",
  "ip": "***",
  "subscription_id": null,
  "phone": null,
  "address": null,
  "customer": null,
  "card": {
    "object": "card",
    "id": "***",
    "date_created": "2016-01-27T01:47:33.000Z",
    "date_updated": "2016-01-27T01:47:33.000Z",
    "brand": "visa",
    "holder_name": "Filipe Deschamps",
    "first_digits": "453222",
    "last_digits": "0610",
    "country": "IT",
    "fingerprint": "***",
    "valid": true
  },
  "metadata": {},
  "antifraud_metadata": {}
}
```

**Comment by filipedeschamps** [comment]
Agora, se eu passo um address em branco, ele reclama:

```
    "customer": {
        "name": "Filipe",
        "email": "kjlfjjf3@dkfjl.com",
        "address": {}
    }
```


Se eu não declarar o address, vai normal:
```
    "customer": {
        "name": "Filipe",
        "email": "kjlfjjf3@dkfjl.com",
    }
```

**Comment by claudiosmweb** [comment]
Entendi, bom ai no caso a galera precisa remover do WooCommerce o resto do endereço então.

Vou adicionar endereço apenas se enviado.

**Comment by claudiosmweb** [comment]
@filipedeschamps pronto, agora apenas nome, sobrenome e e-mail são obrigatórios :p

Se alguém precisar, da para remover os outros campos usando isso:
https://gist.github.com/claudiosmweb/590bf8e9e5d9dd0ba104

Se quiser testar me fala, só você dar ok que posso lançar a nova versão aqui agora.

**Comment by filipedeschamps** [comment]
Sensacional!!

Infelizmente estou no mobile agora e não consigo executar, mas se na sua
conta esta indo as transações, é tiro e queda, pois é como estarão as
outras contas.

**Comment by claudiosmweb** [comment]
Beleza, acabando de traduzir aqui novas strings e já faço deploy então da versão 1.2.3.

**Comment by filipedeschamps** [comment]
Combinado!

**Comment by claudiosmweb** [comment]
Foi https://wordpress.org/plugins/woocommerce-pagarme/

**Comment by filipedeschamps** [comment]
Cara matou a pau!!!! Valeu :)

**Comment by allysonsouza** [comment]
Acabei de instalar a última versão do WooCommerce Pagarme e, apesar de nenhuma notificação de dependência, na realização do checkout ele deu alertas de que faltava número e bairro, apesar dos campos não existirem.

Resolveu instalando o Extra Checkout Fields for Brazil.

**Comment by claudiosmweb** [comment]
@allysonsouza porque a conta ainda precisa dos campos, removi as notificações porque não precisa mais se sua conta do pagar.me estiver configurada.

**Comment by allysonsouza** [comment]
Ah, entendi @claudiosmweb, valeu.
