### ISSUE TITLE
Compatibilidade com WooCommerce 2.5.1

### ISSUE THREAD

**Issue by filipedeschamps** [claudiosmweb/woocommerce-pagarme#13]
@claudiosmweb tudo bem meu caro?

Estamos recebendo alguns retornos sobre a incompatibilidade com a versão 2.5.1 do WooCommerce. Você sabe dizer se esta versão apresenta alguma breaking change?

Muito obrigado :+1:

**Comment by claudiosmweb** [comment]
Na real não, esta funcionando, mas teve problemas com o W3 Total Cache por exemplo, ele quebrou o checkout.

**Comment by filipedeschamps** [comment]
Que estranho, ao instalar tudo pelo wordpress recebo toda hora a mensagem como esta:

![image](https://cloud.githubusercontent.com/assets/4248081/12598943/bba96308-c474-11e5-9fe3-42c0829c94a4.png)

E estou de fato com todas as últimas versões.

**Comment by filipedeschamps** [comment]
Opa, desculpa, isto era em outra issue. Vou recadastrar lá

**Comment by claudiosmweb** [comment]
Acabei de testar aqui de novo e esta funcionando como deveria.
