### ISSUE TITLE
Integrar o Checkout Pagar.me

### ISSUE THREAD

**Issue by claudiosmweb** [claudiosmweb/woocommerce-pagarme#17]
https://docs.pagar.me/checkout/

**Comment by filipedeschamps** [comment]
@claudiosmweb sensacional, este é um recurso que os clientes do Pagar.me sempre requisitam.

Em paralelo, cada vez mais estou aprofundando a análise de todos os módulos do ecosistema e caramba, como os seus são bem desenvolvidos... é um ponto fora da curva :+1:

**Comment by filipedeschamps** [comment]
Sensacional
