### ISSUE TITLE
Adicionar uma action no método 'process_payment'

### ISSUE THREAD

**Issue by mariovalney** [claudiosmweb/woocommerce-pagarme#19]
Seria interessante ter essa action caso o desenvolvedor precise executar algum código após o resultado da transação (api->do_transaction).

Se fugir demais do escopo 'woocommerce', por favor, desconsiderar :D

**Comment by claudiosmweb** [comment]
Não faz sentido ter um action ai, não tem o que executar nesse momento.

**Comment by claudiosmweb** [comment]
Claro, se me mostrar exemplos posso pensar se é valido.
