### ISSUE TITLE
Erro: transaction não encontrada

### ISSUE THREAD

**Issue by filipedeschamps** [claudiosmweb/woocommerce-pagarme#20]
@claudiosmweb tudo bem meu caro?

Um número considerável de usuários estão reportando mensagens como `transaction não encontrada` no momento da compra e pelos testes que fizemos, pode estar relacionada a nova opção de utilizar o Checkout Pagar.me.

Analisando os logs no nosso servidor, notamos que a captura está vindo sem o `transaction_id`, por exemplo na rota de captura.

Você tem alguma pista se pode estar relacionada com a nova implementação?

Obrigado!

**Comment by claudiosmweb** [comment]
Estou vendo erros de JavaScript que esta impedindo abrir o Checkout Pagar.me e tentando enviar de uma vez.

**Comment by rodrigoPgSup** [comment]
Olá Claudio, como vai?

Alguma novidade quanto à falha?


Att.

**Comment by rodrigoPgSup** [comment]
@claudiosmweb

**Comment by claudiosmweb** [comment]
@rodrigoPgSup não precisa de spam velho!

**Comment by rodrigoPgSup** [comment]
Olá @claudiosmweb,

Desculpe se te atrapalho de alguma forma ou se você entendeu como spam. Estou ciente de que você é um profissional extremamente competente e ocupado, só gostaria de saber qual o status da tratativa deste problema.

Att.

**Comment by claudiosmweb** [comment]
@rodrigoPgSup recebo todas as mensagens daqui por e-mail, push e etc, enviar duas vezes a mesma coisa só para me chamar atenção é spam sim!

**Comment by claudiosmweb** [comment]
@filipedeschamps pronto, fiz a correção adequada e agora esta funcionando como deveria.
Acabei de lançar a versão 2.0.2.
