### ISSUE TITLE
Desconto no boleto

### ISSUE THREAD

**Issue by juniorthiesen** [claudiosmweb/woocommerce-pagarme#21]
Claudio tem como adicionar desconto no boleto! Obrigado 

Atenciosamente 
Junior

**Comment by claudiosmweb** [comment]
Pode utilizar este plugin para dr descontos no boleto: https://wordpress.org/plugins/woocommerce-payment-discounts/

**Comment by brunohcury** [comment]
Cláudio tem como através deste plugin configurar para não dar desconto para determinado produto?

**Comment by diegofcv** [comment]
Realmente o desconto específico para o Boleto no PagSeguro seria interessante. O PagSeguro diz que isto é possível sendo passado como um parâmetro na API, então fica o pedido de implementação, se ppossível.

Ref: https://comunidade.pagseguro.uol.com.br/hc/pt-br/community/posts/360001585873-Desconto-no-Boleto-%C3%A1-vista

**Comment by rbarcelo** [comment]
Olá @claudiosanches tudo bem? utilizo a vários anos seu plug-in https://wordpress.org/plugins/woocommerce-payment-discounts/ só que de um tempo para aqui acontece que ao escolher a pessoa boleto como método de pagamento funciona OK, só que se o cliente muda e marca Cartão de Crédito. O desconto gerado pelo boleto continua.  Vários clientes fazem compra pelo cartão com o desconto gerado pelo boleto que era a forma de pagamento escolhida originalmente.
Muito Obrigado
