### ISSUE TITLE
[Checkout Pagar.me] "Valor inválido. Transação desfeita."

### ISSUE THREAD

**Issue by claudiosmweb** [claudiosmweb/woocommerce-pagarme#27]
@filipedeschamps chegou ver alguém com algum erro similar a este?

https://wordpress.org/support/topic/erro-no-parcelamento-com-juros?replies=2#post-8392512

**Comment by rodrigoPgSup** [comment]
Olá @claudiosmweb , 

Sim, e o valor sendo passado no `capture` é diferente do autorizado, ele não chega com o valor de juros, daí a transação é recusada, percebi que o método `generate_checkout_data` não atualiza o amount + interest rate. Pode dar uma olhada nisso?



Obrigado fera!

**Comment by claudiosmweb** [comment]
@rodrigoPgSup então, mas como fazer isso?
Porque é criado o objeto do checkout usando por exemplo:

```
var params = {"customerData":false, "amount":"10000", "createToken": "true", "interestRate": 10 };
checkout.open(params);
```

Isso vai aplicar 10% de juros em cada parcela em cima desses mil reais... Vai mostrar o select das parcelas dentro do modal... 
Mas onde eu recupero isso?
Como eu sei o total de parcelas selecionadas pelo cliente?

**Comment by rodrigoPgSup** [comment]
Olá @claudiosmweb , 

Vai ter que chamar o endpoint para retornar transações na API Pagar.Me com o token gerado pelo Checkout. GET https://api.pagar.me/1/transactions/:id . O que acha?

**Comment by claudiosmweb** [comment]
@rodrigoPgSup muito obrigado, tudo resolvido agora :)
