### ISSUE TITLE
Validação de campos é feita somente após aprovação do pagamento

### ISSUE THREAD

**Issue by stefanfuchs** [claudiosmweb/woocommerce-pagarme#28]
Utilizando o checkout pagar-me, está ocorrendo a seguinte situação: eu clico em "Finalizar compra" e a janela modal do pagar.me abre antes do woocommerce fazer a validação dos campos de cadastro.

Só depois de o pagar.me **aprovar** a transação o woocommerce verifica os campos de cadastro.
Isso dá problema caso o usuário não tenha preenchido algum campo obrigatório, e com isso a compra não vai pra frente.

Utilizando woocommerce v2.6.3 e plugin pagar.me v2.0.5.

**Comment by claudiosmweb** [comment]
Tenta verificar se tem erros de javascript no seu site e talvez testar com outro tema.

**Comment by stefanfuchs** [comment]
Verifiquei que o problema é com o plugin Tickera (venda de tickets) que estou usando. Os campos de input que o plugin cria não são verificados corretamente.
Ainda não resolvi o problema. Estou usando o pagar.me sem o checkout modal por enquanto.

**Comment by claudiosmweb** [comment]
Tem que resolver com esse outro plugin ai.
