### ISSUE TITLE
Após upgrade para última versão do Wordpress (4.6) o número de parcelas não aparece 

### ISSUE THREAD

**Issue by stefanfuchs** [claudiosmweb/woocommerce-pagarme#30]
Após realizar o upgrade, o número de parcelas não aparece no formulário de pagamento. Conforme screenshot abaixo:
![image](https://cloud.githubusercontent.com/assets/3092650/17945414/25e82038-6a1a-11e6-8c1a-8c3b33c745de.png)
Não tem nenhum item no menu dropdown.

Você chegou a testar o plugin com a versão 4.6 do Wordpress?
Obrigado.

**Comment by claudiosmweb** [comment]
Funciona sem problemas com o WordPress 4.6.
Mas isso é carregado usando JavaScript, então você já verificou o console do seu navegador?

**Comment by stefanfuchs** [comment]
Consegui resolver o problema. Muito estranho, era um problema com a função get/post do PHP. 
Os dados da requisição não estavam sendo enviados para a API do pagar.me (https://api.pagar.me/1/transactions/calculate_installments_amount).

Para resolver eu alterei a função **do_request** no arquivo **class-wc-pagarme-api.php** da maneira abaixo.
Inserindo um **'?' . $data** eu forço o envio dos dados via get.

Caso alguém mais esteja tendo o mesmo problema, acho que vale a pena alterar esse código no master.

```
protected function do_request( $endpoint, $method = 'POST', $data = array(), $headers = array() ) {
		$params = array(
			'method'  => $method,
			'timeout' => 60
		);

		if ( ! empty( $headers ) ) {
			$params['headers'] = $headers;
		}

		if($method == 'GET'){
			return wp_safe_remote_get( $this->get_api_url() . $endpoint . '?' . $data, $params );
		} else {			
			if ( ! empty( $data ) ) {
				$params['body'] = $data;
			}
			return wp_safe_remote_post( $this->get_api_url() . $endpoint, $params );
		}
	}
```

**Comment by edinhojorge** [comment]
Um amigo também estava com problemas e pediu para eu olhar, e seu código resolveu o problema. Será que uma versão diferente do PHP ou até SO poderia gerar este comportamento?
Não sou expert em PHP, mas vale a pena olhar.
Obrigado mesmo assim.
Eder

**Comment by stefanfuchs** [comment]
Olá Eder, bom saber que pude ajudar. =)
que versão do PHP ele está usando? E quando começou o problema?
Eu estou com a versão 5.6.24.

Achei algo bem interessante olhando nos [changelogs](http://www.php.net/ChangeLog-5.php#5.6.24) do PHP. Esta [correção do bug #71936](https://bugs.php.net/patch-display.php?bug_id=71936&patch=http_raw_post_data_fix.patch&revision=latest) em específico mexe no código das requisições post e get.

Repare que a modificação é bem na parte de cópia dos dados:

```
+			if (!data) {
+				data = estrdup("");
+			}
```

Isso aí me acendeu uma luz. 
Eu estou começando a achar que o problema começou quando o meu provedor (Hostgator) atualizou a versão do PHP, não quando eu atualizei o Wordpress.

**Comment by edinhojorge** [comment]
Cara, a versão do server que testei é a  7.0.9, no freehostia.com.

Quanto ao bug, acho que não tem relação, pois é apenas para corrigir um segfault, e apenas quando não existe o recebimento de dados.

Na minha opinião, o ideal seria debugar cada ponto da https://developer.wordpress.org/reference/functions/wp_safe_remote_get/ em diferentes versões de php, e até entre versões diferentes do WP. Tentar achar o ponto entre eles. Vi umas reclamações de pessoas com problema após atualização do WP.

Abs
Eder

**Comment by ludyamano** [comment]
@stefanfuchs estava com o mesmo problema aqui, porém estava utilizando o checkout transparente.  Tive de desabilitar o plugin do Pagar.me e ativar o do PagSeguro. O ajuste no código pareceu corrigir o problema.

O erro começou a acontecer após a atualização para a versão 4.6 do WP. Estou rodando em uma VPS da DO com PHP 5.5.9 e não alteramos de versão do PHP.

**Comment by rodrigoPgSup** [comment]
Boa tarde @claudiosmweb , consegue dar uma olhada nessa questão meu caro? Aplicando a correção do @stefanfuchs ou voltando à versão do método `do_request` ?

**Comment by stefanfuchs** [comment]
@edinhojorge realmente, pensando bem parece que a atualização do PHP não tem relação mesmo.
Agora olhando o changelog da versão 4.6 do Wordpress também tem modificações na API do HTTP. Não cheguei a olhar o código, mas provavelmente deve ser esse o motivo dos problemas.

**Comment by pedrobritto** [comment]
@stefanfuchs Estava com seu mesmo problema, fiz a alteração que você postou acima e agora dá pra gerar parcelas sem qualquer tipo de erro. Estou com o problema desde a atualização 4.6 do WP.

**Comment by claudiosmweb** [comment]
WordPress 4.6 atualizou toda a biblioteca que faz requests e mudaram como as coisas eram feitas, no caso pararam de testar se estava passando uma string antes de colocar no `http_build_query()`, mas agora com a correção que fiz já funciona ok.
