### ISSUE TITLE
Estorno automático quando o cliente utiliza checkout pagar.me

### ISSUE THREAD

**Issue by SocialGroups** [claudiosmweb/woocommerce-pagarme#31]
Olá boa tarde tudo bem ?

Notamos um aumento de reclamações de alguns clientes sobre estorno automático e identificamos que isto esta ocorrendo quando um pedido é feito via checkout pagar.me, aparentemente o problema esta no "smallest installment amount." : 

```
if ( $this->get_smallest_installment() > $installment['installment_amount'] ) {
  if ( 'yes' == $this->gateway->debug ) {
    $this->gateway->log->add( $this->gateway->id, 'Payment divided into a lower amount than permitted for order ' . $order->get_order_number() );
   }
   
   return array( 'error' => __( 'Payment divided into a lower amount than permitted.', 'woocommerce-pagarme' ) );
} 
```

O problema é que se o cliente esta utilizando o checkout pagar.me não tem como o módulo fazer o if para validar o valor mínimo de parcela, pois tudo é calculado dentro do pagar.me via javascript, e caso um cliente selecione uma parcela que seja menor do que o o valor que esta configurado como smallest installments o pedido esta sendo estornado de forma indevida.

Poderia por favor verificar ?

Agradeço desde de já a atenção.
Atenciosamente,
Lucas Santos

**Comment by claudiosmweb** [comment]
Vou dar uma verificada nisso até final de semana.

**Comment by claudiosmweb** [comment]
> O problema é que se o cliente esta utilizando o checkout pagar.me não tem como o módulo fazer o if para validar o valor mínimo de parcela, pois tudo é calculado dentro do pagar.me via javascript

Na verdade tem e esse código esta ai especialmente para o Checkout Pagar.me, você me ajudou a criar ele.

O que estava rolando era isso: #30
Estava com problema para gerar as parcelas e por isso que estava permitindo valores maiores do que o configurado.
