### ISSUE TITLE
Finalização Pagar.Me quando falha pagamento

### ISSUE THREAD

**Issue by andrelmfranco** [claudiosmweb/woocommerce-pagarme#32]
Olá Claudio, primeiramente queria parabenizá-lo pelo ótimo serviço que você vem fazendo para Wordpress no Brasil e no mundo.  Tenho o plugin do pagar.me e não sei se está acontecendo com todos, mas quando o cliente finaliza a compra e dá como falhado ele recebe a mensagem e o email do woocommerce de sucesso. Sugiro, se possível, voltar uma mensagem de falha no pagamento e link para escolher outra opção de pagamento.

**Comment by claudiosmweb** [comment]
No caso falha no pagamento em cartão de crédito?
Usando Checkout Pagar.me ou sem?

**Comment by andrelmfranco** [comment]
Isso, o cliente recebe mensagem e email como se estivesse pago (sucesso) e no woocommerce aparece falhado. O pagamento foi com cartão de credito usando o chekout transparente Pagar.Me

**Comment by claudiosmweb** [comment]
@andrelmfranco o cliente recebe e-mail do WooCommerce dizendo que foi pago, mas no admin quando vai ver o pedido aparece como "falhado"?
E o que aparece no painel do Pagar.me sobre o pedido?

**Comment by andrelmfranco** [comment]
Aparece como não capturado, resposta da operadora 1000, só que os clientes falaram que o meu site deu como aprovado.

**Comment by claudiosmweb** [comment]
Tem como ativar modo de testes no seu site e me passar a URL para verificar?

**Comment by claudiosmweb** [comment]
> só que os clientes falaram que o meu site deu como aprovado.

Me mostra print das notas de um pedido que teve esse problema.

**Comment by andrelmfranco** [comment]
Está em modo teste. se puder me ajudar e ser bem rápido agradeço pois posso ter problemas não estando no modo live. brasiliapet.com.br. Para o teste deve usar a opção pagar com cartão de credito agora.

**Comment by andrelmfranco** [comment]
Desculpe minha ignorância, mas como faço para te enviar o print por aqui?

**Comment by claudiosmweb** [comment]
Só arrastar a imagem no editor aqui que ela já sobe direto por aqui.
Ou clicando em "selecting them".

**Comment by claudiosmweb** [comment]
@andrelmfranco acabei de entrar no seu site e não esta usando o Checkout Pagar.me, esta usando a solução padrão deles transparente.

**Comment by claudiosmweb** [comment]
Esta limitando as vendas por CEP?

**Comment by andrelmfranco** [comment]
sim, limito as vendas por CEP. o checkout realmente é o transparente.

**Comment by claudiosmweb** [comment]
Preciso saber um CEP então para conseguir testar.

**Comment by andrelmfranco** [comment]
71735-101

**Comment by claudiosmweb** [comment]
Consegue me mostrar as notas de um pedido que teve problema?

**Comment by andrelmfranco** [comment]
![image](https://cloud.githubusercontent.com/assets/22372502/18771160/079a62d4-8113-11e6-9783-3e138f3b8bf3.png)

**Comment by claudiosmweb** [comment]
Acabei de testar e o checkout esta ok.
O que aconteceu com você é que o pedido passou, mas depois foi rejeitado provavelmente pelo antifraude.
E por isso foi cancelado depois.
O cliente recebeu e-mails porque até então realmente tinha funcionado no inicio, mas depois que o antifraude acusou problema, o valor da transação não foi capturado e por isso que cancelou.

No WooCommerce por padrão não é enviado e-mail para o cliente quando isso acontece, algo que deve mudar nas próximas versões.
Mas desde a versão 2.5 do WooCommerce tem configurações para você receber e-mails quando isso acontece em `wp-admin/admin.php?page=wc-settings&tab=email&section=wc_email_failed_order`.
Assim você é avisado quando isso acontece e pode enviar e-mail para o cliente informando sobre o problema.

Mas até então não tem nada de errado com este plugin ou com o Pagar.me.

**Comment by andrelmfranco** [comment]
Ok Claudio, obrigado pelo pronto atendimento e por enquanto farei o que você sugeriu. Assim que puder farei minha contribuição pelo seu excelente trabalho. Muito obrigado e até a próxima.

**Comment by ThiagoFTelles** [comment]
Olá Claudio! Primeiramente obrigado pelo trabalho foda que você faz na comunidade.
Gostaria de dizer que hoje, em 2020, com WP e WC atualizados acontece que quando eu coloco um dado do cartão errado (de propósito para testes de erros em modo de produção) o pagar.me me informa sucesso porém o pedido falha no painel de pedidos do WC.

Ou seja, neste caso ainda é necessário enviar um e-mail manualmente para o cliente.

**Comment by agenciaspartans** [comment]
Alguém poderia me ajudar? Estou tendo problema no pagarme com woocommerce, o parametro está sendo processado como 'false' e não está sendo capturado, está recusando cartões.

**Comment by csantosrj** [comment]
Boa tarde, ja usei este plugin há algum tempo, consegue garantir que todos os dados referente ao dono do cartão e a comprar estão a ir para pagar-me? consegue ver o motivo da recusa? analisar isso podes saber como agir para de recusar a compra.
