### ISSUE TITLE
Update plugin on the wordpress plugins page

### ISSUE THREAD

**Issue by rfviolato** [claudiosmweb/woocommerce-pagarme#4]
https://wordpress.org/plugins/woocommerce-pagarme/
Tem que atualizar lá ou o source vem do repositório?
De qualquer forma, fico no aguardo pra poder avisar os usuários do plugin :)

**Comment by claudiosmweb** [comment]
@rfviolato tem que atualizar lá, vou gerar o release novo daqui a pouco.

**Comment by rfviolato** [comment]
Vlw, cara! :D
