### ISSUE TITLE
Incompatibilidade com WooCommerce 2.4.10

### ISSUE THREAD

**Issue by filipedeschamps** [claudiosmweb/woocommerce-pagarme#5]
@claudiosmweb bom dia, tudo bem?

Você sabe se aconteceu alguma breaking change com a versão 2.4.10?

Algumas pessoas estão reportando este erro:

``` php
Erro: SyntaxError: Unexpected token <
```

**Comment by claudiosmweb** [comment]
Não e esse erro e generico, no caso qualquer coisa que esteja lançando erro vai quebrar o gateay.
Além que isso só acontece se você esta rodando em produção um site com opções de debug do PHP ativadas... O que é inseguro e não deveria estar acontecendo.

**Comment by filipedeschamps** [comment]
@claudiosmweb muito obrigado pelo retorno meu caro!

Veja o posicionamento do cliente:

```
Testei as versões e o problema surgiu a partir da versão 
1.2.1. Na versão 1.2.1 foi corrigido o método que manipula os retornos 
do Pagar.me, e na 
1.2.2 foi atualizada URL da biblioteca JavaScript do 
Pagar.me.

Ou seja, da versão 1.2.0 para trás aparentemente está 
funcionando.
```

**Comment by claudiosmweb** [comment]
Isso que o cliente falou é igual "blablablabla".
Tem que ativar o modo de debug do WordPress e ver realmente o que esta causando o problema.
https://codex.wordpress.org/Debugging_in_WordPress

**Comment by IvanB8** [comment]
Boa tarde Claudio, tudo bem amigo?

O problema que estou tendo é mais precisamente na página "/order-pay/", do template form-pay.php. O pagamento é processado na página checkout, e sendo negado, depois na página "minha-conta" fica a opção para o cliente tentar pagar novamente na, indo para a "/order-pay". Na página "/order-pay" todas as duas opções de pagamento exibem o mesmo erro, ou seja, "SyntaxError: Unexpected token <". Logo após a exibição do erro, caso tente novamente, aparece a mensagem "Desculpe, sua sessão expirou. Retornar para a página inicial" e ao retornar a "minha-página" o pedido é excluído, sumindo.

Tentativas:
-Desativei todos os meus plugins um por um realizando as operações citadas acima a cada plugin desativado;
-Meu WP não estava com os logs ativados e eu também realizei a alteração indicada no link: https://wordpress.org/support/topic/24-common-issue-syntaxerror-unexpected-token ;
-Mantenho WP, WC e tema sempre atualizados;
-Acompanhei os logs do Woocommerce e do Plugin Pagar.me e não consegui detectar nada. Desabilitei os logs e não tenho mais eles (besteira minha).

OBS: ainda não testei as transações em modo de produção.

Você pode me indicar algum caminho Claudio? Só uma luz? 
Imagino que o problema seja comigo mesmo, porém estou realmente perdido.

Agradeço sua disponibilidade em nos responder aqui!

Ivan.

**Comment by claudiosmweb** [comment]
@IvanB8 o que aparece no log?

**Comment by IvanB8** [comment]
No log do Pagar.me está dando isso Claudio:

[Log erro pagarme-a.txt](https://github.com/claudiosmweb/woocommerce-pagarme/files/34318/Log.erro.pagarme-a.txt)

**Comment by claudiosmweb** [comment]
Log do WordPress.

**Comment by IvanB8** [comment]
Desculpe a falha Claudio. Segue o Log do Wordpress...
[debug.txt](https://github.com/claudiosmweb/woocommerce-pagarme/files/34584/debug.txt)

**Comment by claudiosmweb** [comment]
Parece que você esta enviando a data de aniversário de forma errada.
Tente desativar essa opção e testar de novo.
Mas também tem uma porrada de entradas sobre o plugin `query-monitor`. desative ele e tente de novo também.

**Comment by IvanB8** [comment]
Eu desativei Query Monitor e os erros pararam de aparecer no Debug. Agora vou tentar ver essa questão da data também...

**Comment by IvanB8** [comment]
Nada... Mesmo desativando a data de aniversário recebo o mesmo erro... O pagamento acontece mas eu recebo a mesma mensagem... Após desativar o Query Monitor não aparece mais nada no Debug...

**Comment by IvanB8** [comment]
[debug.txt](https://github.com/claudiosmweb/woocommerce-pagarme/files/34674/debug.txt)

**Comment by claudiosmweb** [comment]
Não entendi, mesmo desativando os dois aparece aquele erro?
Então abra o console do seu browser em network, tente fazer o pagamento novamente, você vai ver aparecendo a consulta ajax para o pagamento.
No console você vai conseguir ver o erro inteiro do que esta acontecendo olhando para a resposta disso.

**Comment by IvanB8** [comment]
O erro da data de aniversário parou de aparecer antes mesmo de desabilitar o Query Monitor. Apareceu uma vez só. Apareceu um erro redirecionamento no form-login, eu arrumei e ele parou de aparecer também. Depois eu desabilitei o Query Monitor e agora não aparece mais nenhum erro no Log do WP.
Um pergunta: eu utilizo o seu plugin WooCommerce Extra Checkout Fields for Brazil que é requisito para para o Pagar.me, porém uso ele sem a opção de mascara, isso pode ter alguma relação?
Estou avaliando em Network e ainda não consegui identificar nada pois não tenho experiência com isso...

**Comment by claudiosmweb** [comment]
Se esta aparecendo `SyntaxError: Unexpected token <`, é porque estava esperando um json, entretanto esta retornando algum erro.
Por isso que é 100% certo que da para ver pela aba de Network consultando a resposta desse request por ajax.

**Comment by IvanB8** [comment]
![pagar me-ajax](https://cloud.githubusercontent.com/assets/15837238/11165259/731666a2-8af1-11e5-8b9a-162f24804e78.jpg)

**Comment by IvanB8** [comment]
![pagar me-ajax2](https://cloud.githubusercontent.com/assets/15837238/11165303/850cbea0-8af2-11e5-9cc3-27d41d326c6e.jpg)

**Comment by claudiosmweb** [comment]
Usando isso errado jovem, EXTREMAMENTE errado!
Tem que clicar e verificar a RESPOSTA em RESPONSE:

![screenshot from 2015-11-14 17-24-05](https://cloud.githubusercontent.com/assets/1264099/11165392/908dfa44-8af4-11e5-8efd-160be92d73c4.png)

**Comment by IvanB8** [comment]
Boa tarde Claudio.
Consegui resolver aqui por enquanto. Muito obrigado pela sua atenção cara, me ajudou bastante e acabei encontrando um caminho.

Obrigado pelo apoio Filipe!

**Comment by filipedeschamps** [comment]
Show de bola :+1:

**Comment by claudiosmweb** [comment]
@IvanB8 e qual era o problema?

**Comment by IvanB8** [comment]
O problema era comigo mesmo. Subi o tema nativo, zerado, e ele funcionou normalmente não apresentando os erros que falei. Depois varri o site e encontrei um class float que coloquei no form-pay.php e ele que gerou o erro "SyntaxError: Unexpected token <". Agora o erro parou de aparecer no site, porém nos logs do WP o erro "woocommerce-pagarme/includes/class-wc-pagarme-api.php on line 242" do campo de aniversário ainda persiste.
No site uma questão persiste:
Quando o pagamento é negado no template "form-pay.php" em "MInha Conta", o site redireciona para a página "thankyou.php" onde deveria aparece a mensagem de pedido falhado, mas exibe a mensagem de pedido recebido. No status do pedido na página minha conta aparece o falhado. Estudei a página thankyou.php, tentei alguma aterações no código <?php if ( $order->has_status( 'failed' ) ) : ?> e não consegui arrumar ainda.

Tudo indica que foi alguma alteração minha durante a criação do site que está resultando nisso. Ainda estou tentando resolver essas últimas questões, mas pelo menos o site está funcionando.

Se puder dar mais algum toque sobre o redirecionamento na thankyou.php fico muito agradecido.

**Comment by claudiosmweb** [comment]
@IvanB8 da data de aniversário vou ver. sobre dizer que recebeu o pedido, não significa que esta confirmado, acontece que cancela depois ao receber o IPN que vai receber algum tempo depois de ter redirecionado para a página.
