### ISSUE TITLE
Tradução de Checkout 

### ISSUE THREAD

**Issue by pganarodriguez** [claudiosmweb/woocommerce-pagarme#6]
Oi Claudio! Sou comercial do Pagar.me e meu cliente tem uma dúvida pois aceita transações internacionais. 

Gostaria de saber se o plug-in Pagar.me - Woocommerce pode ser traduzido para inglês visto que os clientes são estrangeiros. 

Isso é possível? Como faz?

Abs,

Ana Júlia

**Comment by pganarodriguez** [comment]
@claudiosmweb

**Comment by claudiosmweb** [comment]
O plugin originalmente é em Inglês (en_US) e tem tradução para Português do Brasil (pt_BR).
No caso se a instalação do WordPress dele estiver configurado para qualquer lingua que não seja Português do Brasil, o plugin irá exibir todo o conteúdo em Inglês.

**Comment by pganarodriguez** [comment]
Perfeito @claudiosmweb muito obrigada!

**Comment by pganarodriguez** [comment]
@claudiosmweb Você saberia me dizer existe a possibilidade de tirar o campo "CPF" que já vem no plug-in?

Pois como os clientes serão estrangeiros, gostaríamos de tirar o campo CPF na hora do cadastro para processar a transação.

Com o Pagar.me o CPF só é obrigatório com o antifraude ligado, nesse caso o antifraude será desligado para aceitar cartões internacionais.

Obrigado!

**Comment by claudiosmweb** [comment]
Este plugin não adiciona nenhum campo nos formulários de endereço de cobrança ou de entrega.

**Comment by RenatoBonario** [comment]
@claudiosanches primeiramente, obrigado pelo plugin.

Eu preciso de uma ajuda para traduzí-lo para português, eu já mudei o idioma do wordpress, conferi o idioma do woocommerce e está tudo em pt-br. Mas o plugin continua em inglês. Pode ajudar?

Minha versão do wordpres é a 5.9.2 com php 7.4 e o woocommerce é a versão 6.3.1

**Comment by miscapu** [comment]
@RenatoBonario vc mudou o idioma de seu site após a instalação inicial do WordPress?
Você conseguiu resolver esse procedimento?
