### ISSUE TITLE
Dados de cartão estão faltando

### ISSUE THREAD

**Issue by filipedeschamps** [claudiosmweb/woocommerce-pagarme#7]
@claudiosmweb tudo bem?

Tem um cliente nosso que, no processo de checkout, está recebendo mensagens de erro sobre os dados do cartão de crédito ao selecionar o Pagar.me como meio de pagamento:

![image](https://cloud.githubusercontent.com/assets/4248081/11873919/16a3c7a6-a4c4-11e5-846e-27604743f78d.png)

Você sabe o que pode estar acontecendo?

Muito obrigado meu caro!

**Comment by fgranja** [comment]
Olá Claudio

Se precisar de mais informações, pode pedir.

Abraços

**Comment by claudiosmweb** [comment]
Já tentou com outro tema?
Me parece erro no tema, provavelmente deve ter erros de js no console e por isso que o JS do plugin não consegue mostrar os campos.
