### ISSUE TITLE
Visualização do Boleto após finalização da compra

### ISSUE THREAD

**Issue by redeideia** [claudiosmweb/woocommerce-pagarme#8]
Bom dia!

Estou utilizando o plugin e meus clientes estão tendo uma dificuldade após a finalização da compra em minha loja. 

Após clicarem no botão de finalizar pedido com o método boleto bancário selecionado, o woocommerce carrega a página com os detalhes do pedido, mas não aparece em nenhum local da página a opção de gerar o boleto ou mesmo o link para o boleto.

Verifiquei que o link para geração do boleto vai para o cliente por e-mail, mas muitos clientes estão se perdendo, pois querem e estão acostumados em outros e-commerce à ter a opção de gerar o boleto (imprimir) na tela.

Você tem alguma sugestão para resolver esta questão? Existe uma maneira de aparecer ao menos o link gerado pela pagar.me deste boleto na tela de pedido realizado?

Desde já agradeço a atenção.

**Comment by claudiosmweb** [comment]
> Após clicarem no botão de finalizar pedido com o método boleto bancário selecionado, o woocommerce carrega a página com os detalhes do pedido, mas não aparece em nenhum local da página a opção de gerar o boleto ou mesmo o link para o boleto.

O link aparece em forma de alerta depois de finalizar o pedido.
Se não esta aparecendo, é porque o seu tema esta escondendo o alerta, alguns temas fazem isso, não sei porque razão, mas fazem essa besteira.
Então precisa ser corrigido no seu tema... Teste o tema Storefront caso você queria ver como funciona.

**Comment by redeideia** [comment]
Grato pelo rápido retorno Claudio! 

Estou utilizando atualmente o Storefront, mas vou dar uma atenção melhor às configurações dos alertas. 

Agradeço a sua ajuda.
