### ISSUE TITLE
Erro na integração para pedidos efetuados internamente pelo painel de pedidos no woocommerce

### ISSUE THREAD

**Issue by redeideia** [claudiosmweb/woocommerce-pagarme#9]
Bom dia!

Diariamente faço um ou outro pedido na loja utilizando a opção "adicionar pedido" no painel administrativo do Woocommece.

Consigo finalizar a abertura de um novo pedido, selecionando o meio de pagamento "Pagar.me", mas nada acontece ao salvar o pedido. 

Sabe me dizer se esta inclusão de pedido pelo painel não está integrada com a pagar.me ou é algum erro no meu woocommerce em específico?

Agradeço a atenção.

**Comment by claudiosmweb** [comment]
Não tem erro nenhum, na verdade o WooCommerce não tem nada que faça processar pagamentos se for feito tudo de forma interna pelo admin.

O que pode ser feito é criar o pagamento, deixar como pendente e nas ações escolher para enviar a fatura para o cliente, desta forma ele pode clicar no link do e-mail e pagar no seu site.
